# Generated by Django 3.0.6 on 2021-08-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('skeleton', '0002_create_custom_season_view'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kcreading',
            unique_together={('region', 'season', 'crop', 'period_from', 'period_to')},
        ),
    ]
