# Generated by Django 3.0.6 on 2022-07-27 18:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0003_auto_20210810_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.Season')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.SiteDescription')),
                ('strategytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.StrategyType')),
            ],
            options={
                'unique_together': {('site', 'season', 'strategytype')},
            },
        ),
    ]
