# Generated by Django 3.0.6 on 2022-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0004_seasonstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
