# Generated by Django 3.0.6 on 2022-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0005_farm_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='sentek',
            field=models.BooleanField(default=False),
        ),
    ]
