# Generated by Django 3.0.6 on 2021-08-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_farm_product_readingtype_site_vsw_reading_vsw_strategy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ReadingType',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterModelOptions(
            name='vsw_reading',
            options={'get_latest_by': 'date', 'managed': False, 'ordering': ('-date', 'type')},
        ),
    ]
