# Generated by Django 3.0.6 on 2022-10-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20210810_0544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vsw_strategy',
            table='graphs_strategy_v2',
        ),
    ]
